// <auto-generated />

// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "type", Target = "~T:Integration_Tests_MSTestAssemblyHooks")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S1118:Utility classes should not have public constructors", Justification = "<Pending>", Scope = "type", Target = "~T:Integration_Tests_MSTestAssemblyHooks")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Bug", "S3903:Types should be defined in named namespaces", Justification = "<Pending>", Scope = "type", Target = "~T:Integration_Tests_MSTestAssemblyHooks")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "RCS1110:Declare type inside namespace.", Justification = "<Pending>", Scope = "type", Target = "~T:Integration_Tests_MSTestAssemblyHooks")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name should match first type name", Justification = "<Pending>", Scope = "type", Target = "~T:Integration_Tests_MSTestAssemblyHooks")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1128:Unused \"using\" should be removed", Justification = "<Pending>", Scope = "type", Target = "~T:Integration_Tests_MSTestAssemblyHooks")]
